### ISSUE TITLE
Problem with token types

### ISSUE THREAD

**Issue by s-cork** [skulpt/skulpt_parser#48]
Issue arises in 
"from .a import b"

the `'.'` gets tokenized as an `OP` but it's really a `DOT`
This is the correct output from `tokenize.py` too.

In the cpython version of the parser they don't pass the `string` to `this.expect` they pass the `type`

We need to work out how to fix OP's like this in our own parser.
I imagine a bit like how we changed the type of the Name when we found a keyword.

**Comment by s-cork** [comment]
duplicate of #52 

additional question - should we stick with `this.expect(string)` or instead use `this.expect(type)`
the python_generator uses `string`
the c_generator uses `type`

I figure since we do an `===` we wouldn't gain much by using `.type` over `.string`?

**Comment by albertjan** [comment]
this is done now right?

**Comment by s-cork** [comment]
I don't think it's on master - you were working on it earlier in the tokenizer function?

I might try out `this.expect(type)` and see how it looks at some point

**Comment by s-cork** [comment]
had a look at `this.expect(type: number)` didn't seem worth it
